spring:
  application:
    name: "${name}"

  datasource:
    url: jdbc:postgresql://localhost:5432/recipe_service_db
    username: postgres
    password: password
    hikari:
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 20

  jpa:
    properties:
      hibernate.connection.provider_disables_autocommit: true

  data:
    web:
      pageable:
        max-page-size: 200

    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false

  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: "${name}"
        version: "${version}"

app:
  http-error-message:
    constraints:
      uc_recipe_title:
        title: must be unique
      uc_ingredient_title:
        title: must be unique
      uc_recipe_ingredient_recipe_ingredient:
        ingredient: ingredient already exists in recipe
      chk_recipe_ingredient_quantity_positive:
        quantity: must be positive
    unknown-constraint-message: Constraint violation error

  recipe:
    max-recipe-ingredients: 200