spring:
  application:
    name: "${name}"

  datasource:
    url: jdbc:postgresql://localhost:5432/recipe_service_db
    username: postgres
    password: password

  data:
    web:
      pageable:
        max-page-size: 200

  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: "${name}"
        version: "${version}"

app:
  http-error-message:
    constraints:
      uc_recipe_title:
        title: must be unique
    unknown-constraint-message: Constraint violation error