plugins {
    alias(libs.plugins.springframework.boot) apply false
    alias(libs.plugins.dependency.management) apply false
    alias(libs.plugins.jooq.codegen.gradle) apply false
}

subprojects {
    apply plugin: 'java'

    group = 'ru.homemenu'
    version = '0.0.1'

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    configurations.named('compileOnly') {
        extendsFrom configurations.annotationProcessor
    }

    tasks.named('processResources') {
        expand(project.properties)
    }
}


