services:

  recipe-service-db:
    image: postgres:17.9
    container_name: recipe-service-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: recipe_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - recipe_service_db_data:/var/lib/postgresql/data
    networks:
      - observability
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d recipe_service_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./docker/loki/config/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    networks:
      - observability
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      loki:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    networks:
      - observability
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  recipe_service_db_data:
  loki_data:
  grafana_data:

networks:
  observability:
    name: home-menu-observability
    driver: bridge